; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32doit-devkit-v1]
platform = espressif32
board = esp32doit-devkit-v1
upload_speed = 921600
monitor_speed = 115200
monitor_encoding = utf-8
framework = arduino
build_flags = -DASYNC_TCP_STACK_SIZE=8192
board_build.wdt_timeout = 30s
board_build.partitions = partitions.csv
board_build.embed_txtfiles =
    Data\index.html
    
#build_flags = -DOTA_ENABLED, -DCORE_DEBUG_LEVEL=3
board_upload.maximum_size = 1310720
monitor_filters = esp32_exception_decoder
lib_deps = 
    boschsensortec/BSEC2 @ ^1.6.1480
    https://github.com/mathworks/thingspeak-arduino.git
    boschsensortec/BME68x Sensor library @ ^1.2.40408
    me-no-dev/ESPAsyncWebServer @ ^3.1.0 ; Versión compatible
    me-no-dev/AsyncTCP @ ^1.1.1 ; Versión estable
    bblanchon/ArduinoJson @ ^7.0.0 ; Actualización mayor
upload_port = COM5
board_build.filesystem = spiffs
upload_protocol = esptool
